language: python
python: '3.9'

 addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12

branches:
   only:
      - CI

        #addons:
        #firefox: latest

before install:
   # - wget https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
   # - mkdir geckodriver
   # - tar -xzf geckodriver-v0.27.0-linux64.tar.gz -C geckodriver
   # - export PATH=$PATH:$PWD/geckodriver
   # - geckodriver --version
   # - export MOZ_HEADLESS=1
   # - sudo apt-get update
   # - sudo apt-get --yes purge  postgresql\*
   # - sudo apt-get install -y postgresql-12 postgresql-client-12
   # - sudo /etc/init.d/postgresql restart
   - sudo pg_dropcluster --stop 12 main
   - sudo pg_upgradecluster 11 main
   - sudo pg_ctlcluster 12 main restart
   - sudo pg_dropcluster 11 main

services:
   - postgresql

before_script:
   - pip install -r requirements.txt
   - psql -c 'create database testdb;' -U postgres

env:
  global:
    - DJANGO_SETTINGS_MODULE="checklistmgr.travis_settings"
    - MOZ_HEADLESS=1

script:
   - python3 manage.py test
