# Generated by Django 3.1.7 on 2021-02-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_create_chklst', '0006_auto_20201010_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_key', models.CharField(max_length=30, verbose_name='head key')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Heading',
                'verbose_name_plural': 'Headings',
                'ordering': ['head_key'],
            },
        ),
        migrations.AddIndex(
            model_name='heading',
            index=models.Index(fields=['head_key'], name='I_Headings'),
        ),
        migrations.AddConstraint(
            model_name='heading',
            constraint=models.UniqueConstraint(fields=('head_key',), name='Unique heading'),
        ),
    ]
