# Generated by Django 3.1.7 on 2021-02-28 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0014_auto_20210223_2141'),
        ('app_create_chklst', '0008_auto_20210228_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='heading',
            name='head_company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heading', to='app_user.company'),
        ),
    ]
