# Generated by Django 3.1.7 on 2021-02-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0013_user_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='comp_logo',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Picture'),
        ),
    ]
