# Generated by Django 3.1.7 on 2021-02-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_input_chklst', '0007_auto_20201016_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='mgr_lang',
            field=models.CharField(blank=True, default='FR', max_length=2, verbose_name='Language'),
        ),
    ]
