# Generated by Django 3.1.7 on 2021-02-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_input_chklst', '0008_manager_mgr_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='mgr_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Picture'),
        ),
    ]
