# Generated by Django 3.1.7 on 2021-02-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_input_chklst', '0012_auto_20210222_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='mgr_lang',
            field=models.CharField(choices=[('FR', 'French'), ('EN', 'English')], default='FR', max_length=2, verbose_name='Language'),
        ),
    ]
