# Generated by Django 3.1.7 on 2021-02-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_input_chklst', '0013_auto_20210223_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='mgr_lang',
            field=models.CharField(choices=[('FR', 'FR'), ('EN', 'EN')], default='FR', max_length=2, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='mgr_logo',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='logos/', verbose_name='Logo'),
        ),
    ]
