# Generated by Django 3.1.2 on 2021-01-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_checklist', '0011_auto_20201116_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistdone',
            name='cld_title',
            field=models.CharField(default='XXX', max_length=80, verbose_name='title'),
        ),
    ]
