# Generated by Django 3.1.2 on 2021-01-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_checklist', '0012_checklistdone_cld_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdone',
            name='cld_status',
            field=models.IntegerField(choices=[(0, 'Inprogress'), (1, 'Terminated'), (2, 'Saved')], default=0, verbose_name='Status'),
        ),
    ]
