# Generated by Django 3.1.2 on 2021-01-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_checklist', '0013_auto_20210108_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistdone',
            name='cld_remsave',
            field=models.TextField(default=None, null=True, verbose_name='Categories Remarks'),
        ),
        migrations.AddField(
            model_name='checklistdone',
            name='cld_save',
            field=models.TextField(default=None, null=True, verbose_name='Questions/Replies'),
        ),
    ]
