# Generated by Django 3.1.2 on 2021-01-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_checklist', '0014_auto_20210115_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistdone',
            name='cld_date_valid',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='checklistdone',
            name='cld_reminder',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='checklistdone',
            name='cld_status',
            field=models.IntegerField(choices=[(0, 'Inprogress'), (1, 'Terminated'), (2, 'Deleted'), (3, 'Saved2')], default=0, verbose_name='Status'),
        ),
    ]
