# Generated by Django 3.1.2 on 2021-01-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_checklist', '0015_auto_20210118_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdone',
            name='cld_reminder',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
