# Generated by Django 3.1.2 on 2021-01-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_checklist', '0016_auto_20210118_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdone',
            name='cld_reminder',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
