# Generated by Django 3.1.7 on 2021-02-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_checklist', '0018_auto_20210119_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistdone',
            name='cld_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Other Email'),
        ),
    ]
