# Generated by Django 3.1.7 on 2021-02-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_checklist', '0019_checklistdone_cld_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistdone',
            name='cld_reminder_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='checklistdone',
            name='cld_reminder',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
